name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        commands: |
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller -F main.py
    - name: Compress the release binary
      run: |
        ls ${{ steps.build_image.outputs }}
